### ISSUE TITLE
Can't Upload Same Name Documents to Other Projects

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#70]
When I upload the exact same file name to another project, it increments the version number up one, and doesn't show up in the project I uploaded at.

I originally uploaded Kalen.docx to Fuchsia project.  Then I went to NATO's project page, uploaded Kalen.docx, uploaded successfully, but doesn't show up on Nato's page

![image](https://user-images.githubusercontent.com/19345260/48666840-8826b700-ea97-11e8-838e-3e8a546dbfb1.png)

However, it shows up on Fuchsia's project page
![image](https://user-images.githubusercontent.com/19345260/48666853-b7d5bf00-ea97-11e8-8c8c-8a9b8bc349c7.png)

And now Kalen.docx has multiple versions, even though they could potentially be completely different documents

![image](https://user-images.githubusercontent.com/19345260/48666859-d340ca00-ea97-11e8-906e-f15c09745b9f.png)

**Comment by jatinrampal** [comment]
Container has been implemented to be org wide. As of now, it won't support same name files on different projects since projects being within the same organisation have files being stored into the same container.  Kalen_v1 if implemented based on the project would overwrite the existing Kalen_v1 from a different project.

**Comment by rosekal** [comment]
This could still be an issue if we did release this project, as they will be questioning why they can't upload "project_requirements.docx" to another project
